import Head from "next/head";
import Wiki from "../components/Wiki";

export default function Home() {
  return (
    <div>
      <Head>
        <title>wikimedia-app</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex pt-20 items-center justify-center h-[100%]">
      
        <Wiki />
      </main>
    </div>
  );
}
